name: Content API

on:
  push:
    branches:
      - master
    paths: 
      - './apis/content/**'
  pull_request:
    branches: 
      - master
    paths: 
      - './apis/content/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: content

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download
      working-directory: ./apis/content

    - name: Build
      run: go build -v .
      working-directory: ./apis/content

    - name: Test
      run: go test -v ./...
      working-directory: ./apis/content
